###
POST http://localhost:9099/sqs/message
Content-Type: application/json

{
  "messageGroupId": "A",
  "message" : {
    "id" : "A1"
  }
}

###
POST http://localhost:9099/sqs/message
Content-Type: application/json

{
  "messageGroupId": "A",
  "message" : {
    "id" : "A2"
  }
}

###
POST http://localhost:9099/sqs/message
Content-Type: application/json

{
  "messageGroupId": "A",
  "message" : {
    "id" : "A3"
  }
}

###
POST http://localhost:9099/sqs/message
Content-Type: application/json

{
  "messageGroupId": "A",
  "message" : {
    "id" : "A4"
  }
}

###
POST http://localhost:9099/sqs/message
Content-Type: application/json

{
  "messageGroupId": "A",
  "message" : {
    "id" : "A5"
  }
}

####
#POST http://localhost:9099/sqs/message
#Content-Type: application/json
#
#{
#  "messageGroupId": "2",
#  "message" : {
#    "id" : "21",
#    "body" : "1"
#  }
#}
#
####
#POST http://localhost:9099/sqs/message
#Content-Type: application/json
#
#{
#  "messageGroupId": "2",
#  "message" : {
#    "id" : "22",
#    "body" : "1"
#  }
#}
#
#
####
#POST http://localhost:9099/sqs/message
#Content-Type: application/json
#
#{
#  "messageGroupId": "2",
#  "message" : {
#    "id" : "23",
#    "body" : "1"
#  }
#}

