
###
GET http://localhost:9099/sqs/message/a
Accept: application/json

###
GET http://localhost:9099/sqs/message/b
Accept: application/json

###
GET http://localhost:9099/sqs/message/c
Accept: application/json